# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
  DB_CONNECTION: mysql
  DB_PORT: 3306
  DB_DATABASE: simple_bank
  DB_USERNAME: root
  DB_PASSWORD: root

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: 🔥 Initialize MySQL
      run: sudo systemctl start mysql.service --user=root --password=root

    - name: 📌 Initialize first database
      run: |
        mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: 🚀 Boost user
      run: |
        mysql -e "ALTER USER '${{ env.DB_USER }}'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';" \
        -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v ./...
