# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  MYSQL_DATABASE: simple_bank
  MYSQL_PASSWORD: my-secret-pw
  MYSQL_USER: root

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
 
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.MYSQL_DATABASE }};' -u${{ env.MYSQL_USER }} -p${{ env.MYSQL_PASSWORD }}
          
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install golang-migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate

    - name: Run migration
      run: make mysql_migrateup

    - name: Test
      run: make test
